### ISSUE TITLE
Text not showing with white background

### ISSUE THREAD

**Issue by YuvrajKhavad** [malithmcr/super-awesome-up-vote#2]
Check attachment text now showing with white background.

![hello world wp testing](https://user-images.githubusercontent.com/2893666/50590488-4029eb00-0eb1-11e9-87b9-6f52be4658c3.png)

![up vote wp testing wordpress](https://user-images.githubusercontent.com/2893666/50590564-88e1a400-0eb1-11e9-83db-0e5baf3f5fa7.png)

**Comment by malithmcr** [comment]
Hi @YuvrajKhavad  Thanks for the feedback, I'll check this issue and update the repo.

**Comment by malithmcr** [comment]
could you check it now? I made a CSS fix for this.

**Comment by YuvrajKhavad** [comment]
Yes, Checked looks good. @malithmcr 
![3 wp testing](https://user-images.githubusercontent.com/2893666/50600836-6616b600-0ed8-11e9-973c-eab074bde7db.png)
