### ISSUE TITLE
Count also not working.

### ISSUE THREAD

**Issue by YuvrajKhavad** [malithmcr/super-awesome-up-vote#3]
At first time down count show with (-). Check attachment.
![1 wp testing](https://user-images.githubusercontent.com/2893666/50590817-77e56280-0eb2-11e9-8f65-e058b7804444.png)

And when I click on up thumb and then down thumb count is increasing. Check attachment.
![2 wp testing](https://user-images.githubusercontent.com/2893666/50590897-d6124580-0eb2-11e9-9037-3e704741a5c4.png)

Thanks

**Comment by malithmcr** [comment]
Thanks again, I'll fix it asap, If you have any time feel free to contribute.

**Comment by YuvrajKhavad** [comment]
@malithmcr Yes, Have a plan to contribute to this plugin. Currently checking plugin code.

**Comment by malithmcr** [comment]
> @malithmcr Yes, Have a plan to contribute to this plugin. Currently checking plugin code.

Thank you so much!

**Comment by malithmcr** [comment]
Fixed

**Comment by YuvrajKhavad** [comment]
Counter working. But when refresh page, again counter set at zero. Values not save. @malithmcr 

For more details please check the attached screenshot.

![asdasd wp testing](https://user-images.githubusercontent.com/2893666/50600999-eb9a6600-0ed8-11e9-9f29-6ca19b2fdc0f.png)

![ssdfsd](https://user-images.githubusercontent.com/2893666/50601013-f48b3780-0ed8-11e9-9ecd-b5aae05b2915.png)

**Comment by malithmcr** [comment]
Thank you I'll take a look
